version: '3'
services:
    rabbitmq:
        image: rabbitmq:management-alpine
        container_name: rabbitmq
        environment:
            - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
            - RABBITMQ_DEFAULT_USER=sabadell
            - RABBITMQ_DEFAULT_PASS=paracuru
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - network
    database:
        image: postgres:alpine
        container_name: postgres
        ports:
            - 15432:5432
        environment:
            - POSTGRES_USER=sabadell
            - POSTGRES_PASSWORD=password
        networks:
            - network
    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: zookeeper
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - network
    kafka1:
        image: bitnami/kafka:latest
        container_name: kafka1
        ports:
            - 9092:9092
            - 29092:29092
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
        networks:
            - network
        depends_on:
            - zookeeper
    kafka2:
        image: bitnami/kafka:latest
        container_name: kafka2
        ports:
            - 9093:9092
            - 29093:29092
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29093
        networks:
            - network
        depends_on:
            - zookeeper
    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        container_name: kafdrop
        ports:
            - 9000:9000
        environment:
            -  KAFKA_BROKERCONNECT=kafka1:9092,kafka2:9093
        networks:
            - network
        depends_on:
            - kafka1
            - kafka2
    consul:
        image: bitnami/consul:latest
        container_name: consul
        ports:
            - '8300:8300'
            - '8301:8301'
            - '8301:8301/udp'
            - '8500:8500'
            - '8600:8600'
            - '8600:8600/udp'
        networks:
            - network
networks:
    network: 
        driver: bridge
