server:
  port: 0
spring:
  application:
    name: user-query
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres
    username: sabadell_userq
    password: sabadell_userq
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: user_query
management:
  endpoint:
    health.show-details: always
  endpoints:
    web.exposure.include: '*'
