server:
  port: 0
spring:
  application:
    name: order-command
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    stream:
      kafka:
        binder:
          brokers: localhost:29092,localhost:29093
          minPartitionCount: 2
          replicationFactor: 2
      bindings:
        input-update:
          destination: order-update
          group: ${spring.application.name}
          binder: kafka
        output-merge:
          destination: order-merge
          binder: kafka
        output-process:
          destination: order-process
          binder: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: sabadell
    password: paracuru
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres
    username: sabadell_orderc
    password: sabadell_orderc
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: order_command
management:
  endpoint:
    health.show-details: always
  endpoints:
    web.exposure.include: '*'