server:
  port: 0
spring:
  application:
    name: order-proxy
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    stream:
      bindings:
        output:
          destination: order-process
management:
  endpoint:
    health.show-details: always
  endpoints:
    web.exposure.include: '*'
