server:
  port: 0
spring:
  application:
    name: order-query
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    stream:
      kafka:
        binder:
          brokers: localhost:29092,localhost:29093
          minPartitionCount: 2
          replicationFactor: 2
      bindings:
        input:
          destination: order-merge
          group: ${spring.application.name}
          binder: kafka
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres
    username: sabadell_orderq
    password: sabadell_orderq
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: order_query
management:
  endpoint:
    health.show-details: always
  endpoints:
    web.exposure.include: '*'